[package]
name = "asm"
version = "0.1.0"
authors = ["NoCtrlZ <phantomofrotten@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
pairing_bn256 = { version = "0.1.0", path = ".." }
